<?php

use Cissee\Webtrees\Module\ResearchSuggestions\TomSelectSourceWithSuggestions;
use Fisharebest\Webtrees\Http\RequestHandlers\TomSelectSource;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var string      $at     "@" or "" (or unset).
 * @var Source|null $source
 * @var string|null $class
 * @var string|null $id
 * @var string      $name
 * @var Tree        $tree
 */

$at = $at ?? '';

$defaultUrl = route(TomSelectSource::class, ['tree' => $tree->name(), 'at' => $at]);
$adjustedUrl = route(TomSelectSourceWithSuggestions::class, ['tree' => $tree->name(), 'at' => $at]);

?>

<select
    autocomplete="off"
    class="form-select tom-select-sws <?= $class ?? '' ?>"
    <?php
    //data-url="_" set dynamically
    ?>
    data-default-url="<?= $defaultUrl ?>"
    data-adjusted-url="<?= $adjustedUrl ?>"
    
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($source ?? null) instanceof Source) : ?>
        <option value="<?= e($at . $source->xref() . $at) ?>">
            <?= view('selects/source', ['source' => $source]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>

<?php View::push('javascript') ?>
<script>
<?php
//do not use like this, as in webtrees.js: anyway not here (could initi in webtreesExt though):
//would initialize repeatedly if there are multiple sources
//document.querySelectorAll('.tom-select-sws').forEach(element => webtrees.initializeTomSelectSWS(element));
?>
$(function () {
    var element = document.querySelector('#'+CSS.escape('<?= e($id ?? $name) ?>'));
    webtrees.initializeTomSelectSWS(element);
});
</script>
<?php View::endpush() ?>
