<?php

use Cissee\WebtreesExt\MoreI18N;

//original view (easier to monkeypatch than to extend properly)
ob_start();
echo view('::admin/trees-preferences', [
            'all_fam_facts'            => $all_fam_facts,
            'all_indi_facts'           => $all_indi_facts,
            'all_name_facts'           => $all_name_facts,
            'all_plac_facts'           => $all_plac_facts,
            'all_repo_facts'           => $all_repo_facts,
            'all_sour_facts'           => $all_sour_facts,
            'all_surname_traditions'   => $all_surname_traditions,
            'base_url'                 => $base_url,
            'calendar_formats'         => $calendar_formats,
            'data_folder'              => $data_folder,
            'formats'                  => $formats,
            'french_calendar_end'      => $french_calendar_end,
            'french_calendar_start'    => $french_calendar_start,
            'gregorian_calendar_start' => $gregorian_calendar_start,
            'members'                  => $members,
            'page_layouts'             => $page_layouts,
            'pedigree_individual'      => $pedigree_individual,
            'privacy_options'          => $privacy_options,
            'relatives_events'         => $relatives_events,
            'source_types'             => $source_types,
            'surname_list_styles'      => $surname_list_styles,
            'theme_options'            => $theme_options,
            'title'                    => $title,
            'tree'                     => $tree,
            'tree_count'               => $tree_count,
        ]);

$parentHtml = ob_get_clean();

$search = "<h3>" . MoreI18N::xlate('Facts for repository records') . "</h3>";

$all_sour_data_even_facts = array_merge($all_indi_facts, $all_fam_facts);

$ext = view('admin/trees-preferences-ext', [
            'tree'                     => $tree,
            'all_sour_data_even_facts' => $all_sour_data_even_facts,
        ]);

$adjustedHtml = str_replace($search, $ext . $search, $parentHtml);

echo $adjustedHtml;

?>
