<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Functions\FunctionsEdit;

?>

<div class="card mb-4">
    <a class="card-header" href="#" data-toggle="collapse" data-target="#add-sour-data-even-object" aria-expanded="false" aria-controls="add-sour-data-even-object">
        <?= MoreI18N::xlate('Add an event') ?>
    </a>

    <div class="card-body collapse" id="add-sour-data-even-object">
        <?= FunctionsEdit::addSimpleTag($tree, 2 . ' EVEN', 'DATA') ?>
        <?= FunctionsEdit::addSimpleTag($tree, 3 . ' DATE') ?>
        <?= FunctionsEdit::addSimpleTag($tree, 3 . ' PLAC') ?>
    </div>
</div>
